import { Tool } from "@/types";

export const TOOLS: Tool[] = [
  {
    id: "hex-converter",
    name: "Hex Calculator",
    description:
      "Convert between hexadecimal, decimal, binary, and octal number systems",
    category: "converter",
    icon: "Calculator",
    href: "/tools/hex-converter",
    featured: true,
    keywords: [
      "hex",
      "十六进制",
      "二进制",
      "八进制",
      "十进制",
      "进制转换",
      "calculator",
      "计算器",
      "binary",
      "decimal",
      "octal",
    ],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPG, PNG, WebP, and other formats",
    category: "image",
    icon: "Image",
    href: "/tools/image-converter",
    featured: true,
    keywords: [
      "图片",
      "图像",
      "转换",
      "格式",
      "jpg",
      "png",
      "webp",
      "image",
      "convert",
      "照片",
    ],
  },
  {
    id: "ocr",
    name: "OCR Tool",
    description: "Extract text from images using optical character recognition",
    category: "image",
    icon: "ScanText",
    href: "/tools/ocr",
    featured: true,
    keywords: [
      "ocr",
      "文字识别",
      "图片识别",
      "提取文字",
      "扫描",
      "识别",
      "文本",
      "extract",
      "text",
      "scan",
    ],
  },
  {
    id: "model-viewer",
    name: "3D Model Viewer",
    description: "View and interact with 3D models in your browser",
    category: "3d",
    icon: "Box",
    href: "/tools/model-viewer",
    featured: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode text to/from Base64 format",
    category: "text",
    icon: "Binary",
    href: "/tools/text-utils",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes from text",
    category: "text",
    icon: "Hash",
    href: "/tools/text-utils",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    category: "text",
    icon: "FileJson",
    href: "/tools/json-formatter",
    featured: true,
    keywords: [
      "json",
      "格式化",
      "验证",
      "压缩",
      "format",
      "validate",
      "minify",
    ],
  },
  {
    id: "text-compressor",
    name: "Text Compressor",
    description: "Compress multi-line text into single line",
    category: "text",
    icon: "Minimize2",
    href: "/tools/text-compressor",
    featured: true,
    keywords: ["文本", "压缩", "单行", "text", "compress", "minify"],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords or memorable passphrases",
    category: "security",
    icon: "Key",
    href: "/tools/password-generator",
    featured: true,
    keywords: [
      "密码",
      "生成",
      "安全",
      "password",
      "generate",
      "security",
      "随机",
    ],
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between color formats",
    category: "design",
    icon: "Palette",
    href: "/tools/color-picker",
    featured: true,
    keywords: [
      "颜色",
      "色彩",
      "拾取",
      "color",
      "picker",
      "hex",
      "rgb",
      "调色板",
    ],
  },
  {
    id: "linux-cheatsheet",
    name: "Linux Cheatsheet",
    description: "Essential Linux commands with examples",
    category: "developer",
    icon: "Terminal",
    href: "/cheatsheets/linux",
    featured: true,
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to custom dimensions with rotation support",
    category: "image",
    icon: "Scissors",
    href: "/tools/image-cropper",
    featured: true,
  },
  {
    id: "encoder-decoder",
    name: "Encoder/Decoder",
    description: "Encode and decode Base64, URLs, and generate MD5 hashes",
    category: "developer",
    icon: "FileText",
    href: "/tools/encoder-decoder",
    featured: true,
    keywords: [
      "编码",
      "解码",
      "解密",
      "加密",
      "base64",
      "url",
      "md5",
      "encode",
      "decode",
      "hash",
    ],
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Boost your productivity with the Pomodoro Technique",
    category: "productivity",
    icon: "Zap",
    href: "/tools/pomodoro-timer",
    featured: true,
    keywords: [
      "pomodoro",
      "productivity",
      "time management",
      "pomodoro technique",
      "pomodoro timer",
      "时钟",
      "shizhong",
      "fanqie",
      "timer",
      "count",
      "倒计时",
    ],
  },
  {
    id: "cat-gallery",
    name: "Cat Gallery",
    description: "Browse beautiful cat pictures from The Cat API",
    category: "image",
    icon: "Image",
    href: "/tools/cat-gallery",
    featured: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between timestamps and human-readable dates",
    category: "developer",
    icon: "Clock",
    href: "/tools/timestamp-converter",
    featured: true,
  },
  {
    id: "docker-cheatsheet",
    name: "Docker Cheatsheet",
    description: "Quick reference for Docker commands",
    category: "developer",
    icon: "Shell",
    href: "/cheatsheets/docker",
    featured: true,
  },
  {
    id: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Quick reference for Git commands",
    category: "developer",
    icon: "GitBranch",
    href: "/cheatsheets/git",
    featured: true,
  },
  {
    id: "nginx-cheatsheet",
    name: "NGINX Cheatsheet",
    description: "Quick reference for NGINX configurations and commands",
    category: "developer",
    icon: "Server",
    href: "/cheatsheets/nginx",
    featured: true,
  },
  {
    id: "preferences",
    name: "Preferences",
    description: "Manage your preferences and settings",
    category: "developer",
    icon: "Palette",
    href: "/tools/preferences",
    featured: false,
    keywords: [
      "设置",
      "偏好",
      "shezhi",
      "preference",
      "setting",
      "preferences",
      "settings",
    ],
  },
  {
    id: "lottery",
    name: "Lottery Tools",
    description:
      "Lottery prize calculator and number generator for DLT, SSQ, and FC8",
    category: "entertainment",
    icon: "Ticket",
    href: "/tools/lottery",
    featured: true,
    keywords: [
      "彩票",
      "大乐透",
      "双色球",
      "福彩",
      "体彩",
      "lottery",
      "dlt",
      "ssq",
      "奖金",
      "中奖",
      "开奖",
      "号码",
      "识别",
      "OCR",
      "caipiao",
      "daletou",
      "fucai",
      "ticai",
      "模拟",
      "彩票号码",
    ],
  },
];

export const CATEGORIES = [
  { id: "all", name: "All Tools", icon: "LayoutGrid" },
  { id: "converter", name: "Converters", icon: "RefreshCw" },
  { id: "image", name: "Image Tools", icon: "Image" },
  { id: "text", name: "Text Tools", icon: "FileText" },
  { id: "3d", name: "3D Tools", icon: "Box" },
  { id: "security", name: "Security Tools", icon: "Shield" },
  { id: "design", name: "Design Tools", icon: "Palette" },
  { id: "developer", name: "Developer", icon: "Code" },
  { id: "productivity", name: "Productivity", icon: "Zap" },
  { id: "entertainment", name: "Entertainment", icon: "Sparkles" },
] as const;
