import { Tool } from "@/types";

export const TOOLS: Tool[] = [
  {
    id: "hex-converter",
    name: "Hex Calculator",
    description:
      "Convert between hexadecimal, decimal, binary, and octal number systems",
    category: "converter",
    icon: "Calculator",
    href: "/tools/hex-converter",
    featured: true,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    description: "Convert images between JPG, PNG, WebP, and other formats",
    category: "image",
    icon: "Image",
    href: "/tools/image-converter",
    featured: true,
  },
  {
    id: "ocr",
    name: "OCR Tool",
    description: "Extract text from images using optical character recognition",
    category: "image",
    icon: "ScanText",
    href: "/tools/ocr",
    featured: true,
  },
  {
    id: "model-viewer",
    name: "3D Model Viewer",
    description: "View and interact with 3D models in your browser",
    category: "3d",
    icon: "Box",
    href: "/tools/model-viewer",
    featured: true,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode text to/from Base64 format",
    category: "text",
    icon: "Binary",
    href: "/tools/text-utils",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes from text",
    category: "text",
    icon: "Hash",
    href: "/tools/text-utils",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    category: "text",
    icon: "FileJson",
    href: "/tools/json-formatter",
    featured: true,
  },
  {
    id: "text-compressor",
    name: "Text Compressor",
    description: "Compress multi-line text into single line",
    category: "text",
    icon: "Minimize2",
    href: "/tools/text-compressor",
    featured: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords or memorable passphrases",
    category: "security",
    icon: "Key",
    href: "/tools/password-generator",
    featured: true,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between color formats",
    category: "design",
    icon: "Palette",
    href: "/tools/color-picker",
    featured: true,
  },
  {
    id: "linux-cheatsheet",
    name: "Linux Cheatsheet",
    description: "Essential Linux commands with examples",
    category: "developer",
    icon: "Terminal",
    href: "/cheatsheets/linux",
    featured: true,
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to custom dimensions with rotation support",
    category: "image",
    icon: "Scissors",
    href: "/tools/image-cropper",
    featured: true,
  },
  {
    id: "encoder-decoder",
    name: "Encoder/Decoder",
    description: "Encode and decode Base64, URLs, and generate MD5 hashes",
    category: "developer",
    icon: "FileText",
    href: "/tools/encoder-decoder",
    featured: true,
  },
  {
    id: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Boost your productivity with the Pomodoro Technique",
    category: "productivity",
    icon: "Zap",
    href: "/tools/pomodoro-timer",
    featured: true,
  },
  {
    id: "cat-gallery",
    name: "Cat Gallery",
    description: "Browse beautiful cat pictures from The Cat API",
    category: "image",
    icon: "Image",
    href: "/tools/cat-gallery",
    featured: true,
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between timestamps and human-readable dates",
    category: "developer",
    icon: "Clock",
    href: "/tools/timestamp-converter",
    featured: true,
  },
  {
    id: "docker-cheatsheet",
    name: "Docker Cheatsheet",
    description: "Quick reference for Docker commands",
    category: "developer",
    icon: "Shell",
    href: "/cheatsheets/docker",
    featured: true,
  },
  {
    id: "git-cheatsheet",
    name: "Git Cheatsheet",
    description: "Quick reference for Git commands",
    category: "developer",
    icon: "GitBranch",
    href: "/cheatsheets/git",
    featured: true,
  },
  {
    id: "nginx-cheatsheet",
    name: "NGINX Cheatsheet",
    description: "Quick reference for NGINX configurations and commands",
    category: "developer",
    icon: "Server",
    href: "/cheatsheets/nginx",
    featured: true,
  },
  {
    id: "preferences",
    name: "Preferences",
    description: "Manage your preferences and settings",
    category: "developer",
    icon: "Palette",
    href: "/tools/preferences",
    featured: false,
  },
];

export const CATEGORIES = [
  { id: "all", name: "All Tools", icon: "LayoutGrid" },
  { id: "converter", name: "Converters", icon: "RefreshCw" },
  { id: "image", name: "Image Tools", icon: "Image" },
  { id: "text", name: "Text Tools", icon: "FileText" },
  { id: "3d", name: "3D Tools", icon: "Box" },
  { id: "security", name: "Security Tools", icon: "Shield" },
  { id: "design", name: "Design Tools", icon: "Palette" },
  { id: "developer", name: "Developer", icon: "Code" },
  { id: "productivity", name: "Productivity", icon: "Zap" },
] as const;
